// Copy the built WASM kernel into dist/ so it ships with the published package and is available to
// the demo. Run as the last step of `npm run build` (after Vite has emptied/written dist). The
// source (asm/build/kernels.wasm) is gitignored and regenerated by `npm run asbuild`.
import { copyFileSync, mkdirSync, existsSync } from 'node:fs';

const src = 'asm/build/kernels.wasm';
const dest = 'dist/kernels.wasm';

if (!existsSync(src)) {
  console.error(`[copy-wasm] ${src} not found — run "npm run asbuild" first`);
  process.exit(1);
}
mkdirSync('dist', { recursive: true });
copyFileSync(src, dest);
console.log(`[copy-wasm] ${src} → ${dest}`);
